<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-6f1a9c
Date:    2017-12-31 08:10:08
Version: v2.1.0
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-6f1a9c",
    "email": {
        "to": "harry.jeffs2222@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "",
        "template": "You receive an email from {sender.fullname}.\n\nThe web form data:\n{dataTable}\n\nReference ID: {AutoID}\nIP: {IP}\nDate: {Date}\nTime: {Time}\nWebsite: {HTTP_HOST}\nReferer: {HTTP_REFERER}\n",
        "fromName": "New contact form - Creationrenovation.com.au"
    },
    "admin": {
        "users": "admin:803da",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Thanks! Your message has been received and an email has been sent to {f2}. We will endeavour to respond as soon as possible. ",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "green"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "f0",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f1",
                    "condition": "!=",
                    "value": ""
                },
                {
                    "disabled": false,
                    "selector": "f2",
                    "condition": "!=",
                    "value": ""
                },
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "!=",
                    "value": ""
                },
                {
                    "disabled": false,
                    "selector": "f3",
                    "condition": "!=",
                    "value": ""
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "Full Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1",
            "labelHide": false
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "5",
                        "msg": "Please enter at least {5} characters."
                    },
                    "maxlength": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                },
                "mainDescription": "",
                "description": ""
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Phone Number",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "alphanumeric": {
                        "enabled": true
                    },
                    "minlength": {
                        "enabled": true,
                        "val": "7",
                        "msg": "Please enter at least {7} numbers."
                    }
                },
                "mask": {
                    "pattern": "#"
                }
            },
            "id": "f4",
            "cid": "c28"
        },
        {
            "label": "Message",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "id": "f3",
            "cid": "c3",
            "labelHide": false
        },
        {
            "label": "Google reCaptcha",
            "field_type": "recaptcha",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "hidden": true
            },
            "labelHide": true,
            "recaptcha": {
                "theme": "dark",
                "siteKey": "6Lcg3T4UAAAAAIFoTHXq0FQ8x2-thmVSb5q8cfs0",
                "secretKey": "6Lcg3T4UAAAAAK8S_EM3MxxbPV9zfOJk626uyDy8",
                "language": "",
                "errMsg": "Google reCaptcha validation error. Please try again.",
                "maxFailed": "10"
            },
            "id": "f5",
            "cid": "c42"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class